save_states_tsv:
  reporter_module: measure.reporters.save_states_to_file
  reporter_function: save
  parameters:
    save_directory: output
    filename: states
    file_type: tsv
    overwrite: true


save_states_csv:
  reporter_module: measure.reporters.save_states_to_file
  reporter_function: save
  parameters:
    save_directory: output
    filename: states
    file_type: csv
    overwrite: true

greenflag_ratio_csv:
  reporter_module: measure.reporters.save_group_info_to_file
  reporter_function: save
  parameters:
    save_directory: output
    filename: greenflag_ratio
    file_type: csv
    overwrite: true
    grouping_value: directory 
    grouping_value_type: meta
    reporting_value: green_flag_to_total_scripts

greenflag_ratio_tsv:
  reporter_module: measure.reporters.save_group_info_to_file
  reporter_function: save
  parameters:
    save_directory: output
    filename: greenflag_ratio
    file_type: tsv
    overwrite: true
    grouping_value: directory 
    grouping_value_type: meta
    reporting_value: green_flag_to_total_scripts
